---
- name: Hello World!
  hosts: all
 
  tasks:
  - name: Hello World!
    shell: echo "Hi! Ansible is working."

  - debug: 
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
