---
- name: Touch a file
  win_file:
    path: C:\Temp\foo.conf
    state: touch
- name: create a directory
  win_file: 
    path: C:\MGS_Download\Temp"
    state: directory    
- name: create a file
  win_file:
    path: C:\MGS_Download\foo.txt
    state: touch
